### ISSUE TITLE
add Steam support

### ISSUE THREAD

**Issue by Steamhelp** [atomizer/muledump#48]
Kabam has prevented further account linking so now muledump doesn't work with steam.
I know this is due to the steam ROTMG client using your steam ID to log in,  which is not an email or password.  Do you think you can possibly update muledump to recognize steam ID, so I can use muledump on the steam version of rotmg?

**Comment by BlackRayquaza** [comment]
@Nightfirecat @atomizer I can play with my steam account on with fash projecter/web.
![](http://i.imgur.com/BT8tybw.png)

I can also view my account on muledump, altough it does show an "email not verified error".
![](http://i.imgur.com/Q3ahnyw.png)

**Comment by ManWithBear** [comment]
@BlackRayquaza can you explain, how you did it?

**Comment by Nightfirecat** [comment]
@BlackRayquaza I'll try to look into this some more in the coming weeks. Thanks for the research, it's already been helpful!

**Comment by BlackRayquaza** [comment]
@Nightfirecat @ManWithBear  https://github.com/atomizer/muledump/pull/78

**Comment by ManWithBear** [comment]
@BlackRayquaza and how to use it?

**Comment by BlackRayquaza** [comment]
@ManWithBear There isnt an easy way to use it, email me or contact me on skype (pkmnwalkthroughes).

**Comment by ManWithBear** [comment]
@BlackRayquaza if you try explain it here, it will help not only me.

**Comment by Nightfirecat** [comment]
Roger roger.

**Comment by atomizer** [comment]
Not closing this until proper docs are in.

**Comment by BlackRayquaza** [comment]
@atomizer Contact me and ill show you how it works

**Comment by Nightfirecat** [comment]
@BlackRayquaza I've still got notes from our testing/verification that I'm planning on writing into documentation. Regardless of whether you get a chance to discuss this with atomizer (probably would be useful either way), this issue is dependent both on the feature being implemented (done :heavy_check_mark:) and documented (not done yet :heavy_multiplication_x:).

@atomizer Seeing as the documentation should probably be a more 'living' document, I'm thinking it would be best implemented as a GitHub wiki page. Agree/disagree?

**Comment by atomizer** [comment]
Yeah, it doesn't matter whether I know. There should be a tutorial that any user can follow, like with kongregate. Good call about the wiki feature, it didn't exist when muledump was created :) Moved most of the readme there.

**Comment by Nightfirecat** [comment]
Problem being with "tutorial that any user can follow" may not be 100% accurate.

Part of the process of getting all of the necessary information is sniffing HTTPS packets with a custom root certificate installed (so that HTTPS can be decoded) to get some information. It's unfortunately not simple, and unless we find a good way to reverse-engineer it, it may not be possible to be made simple.
For the time being, I'll document it in such a way that someone with the same tools as I have (Fiddler & web browser) would be able to do it. I'll do more investigation once that's done as to whether we can imitate a Steam client well enough to get the data we're after.

**Comment by Nightfirecat** [comment]
@atomizer, [Steam Tutorial](https://github.com/atomizer/muledump/wiki/Steam-Tutorial) for using Steamworks credentials.

**Comment by atomizer** [comment]
Good job! We can roll with this.
