### ISSUE TITLE
Refreshing data no longer works after database migration.

### ISSUE THREAD

**Issue by qqwref** [atomizer/muledump#65]
Fix: muledump.js line 15, change from
var URL = 'https://' + ['realmofthemadgod', 'rotmgtesting'][+!!window.testing] + '.appspot.com/char/list?'
to
var URL = 'https://' + ['realmofthemadgodhrd', 'rotmgtesting'][+!!window.testing] + '.appspot.com/char/list?'

**Comment by Nightfirecat** [comment]
Your version of muledump is out of date; there have been updates since the database migration, and [the fix you're describing has already been implemented in realmapi.js](https://github.com/atomizer/muledump/blob/master/lib/realmapi.js#L4).

Download the current code (the same way you did originally) and overwrite the old files, and it should work fine.

**Comment by qqwref** [comment]
Ah, okay, I had 0.4.26 and didn't realize it was still being worked on! Thanks for keeping it up to date :)
