### ISSUE TITLE
No accounts show up when I add the Kongregate credentials

### ISSUE THREAD

**Issue by Loudoan** [atomizer/muledump#86]
Every Kabam account shows up on Muledump, but as soon as I add the credentials to accounts.js nothing shows up anymore and it gives me this error on muledump: "Uncaught SyntaxError: Unexpected token <"

**Comment by Nightfirecat** [comment]
I'm assuming you're using the latest code, as well as [following the instructions in the Kabam tutorial](https://github.com/atomizer/muledump/wiki/Kabam-tutorial)?

Can you bring up your browser console, and check what line number of what file the error occurs at? That would greatly help in debugging this issue.

**Comment by Loudoan** [comment]
accounts.js:2
That's the line I pasted the credentials.

**Comment by atomizer** [comment]
Looks like you broke syntax. Make sure both GUID and secret are in quotes. [Here](https://en.wikipedia.org/wiki/JSON#Example) is an example of a correct JSON object.

**Comment by Loudoan** [comment]
I don't think that's the problem, but here's what it looks like if you want to see for yourself: http://imgur.com/7HwBlGc

**Comment by atomizer** [comment]
First of all, please go and change your kongregate password - you shouldn't have posted a screenshot with your account data unedited.

After you did that:
It might be not clear from instructions, but you need to take the text from between `<GUID>` and `</GUID>` and put it below (on line 10) instead of `e-mail` (keep the quotes!). Same for `<Secret>` part - put it in there as `password`. Also remove the other example lines if you are not using them.
What it should look like:
```js
accounts = {
  'kongretage:yournumbers': 'yoursecret'
}
```

**Comment by Loudoan** [comment]
Looks like I just didn't understand the tutorial, thanks for the help!
