### ISSUE TITLE
One-click Login bug

### ISSUE THREAD

**Issue by GerRudi** [atomizer/muledump#98]
I Still don't have any idea how github works, so I'll use this.

In mulelogin.au3 line 56 there's an underscore_ before 'StringReverse(...)' which will give an error when trying to run the script. The underscore has to be removed as it's not an UDF.

**Comment by Nightfirecat** [comment]
Yes, that was added in 8aafda5; `_StringReverse` used to be a user-defined function used for reversing strings, but was removed in later versions of AutoIt in favor of the native function `StringReverse`. Since we don't do any version checking currently I've implemented a quick-fix that tries both functions if the first attempt fails. You shouldn't be seeing any errors because of it, since either one or the other should run fine. Older versions will use the UDF, and newer versions will use the native function.
